import type { Metadata } from 'next'
import { Roboto, Fredoka } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import Header from '@/components/Header'
import { cn } from '@/lib/utils'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
})

const fredoka = Fredoka({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-fredoka',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn('font-roboto', roboto.variable, fredoka.variable)}>
        <Header />
        <main className="container px-3 md:px-6 pb-12">{children}</main>
        <Toaster />
      </body>
    </html>
  )
}
